version: '1.0'
name: master-pipeline
displayName: C++ CI Build
stages:
  - stage:
    name: compile
    displayName: 编译与测试
    steps:
      - step: build@maven
        name: build_and_test
        displayName: 编译并运行测试
triggers:
  push:
    branches:
      include:
        - master
